language: node_js

node_js:
  - "12"

notifications:
  email: false

cache: yarn

before_script:
  - ruby -p -i.orig -e 'gsub("/root/blog-generator.js", Dir.pwd)' test/snapshot.yml

script:
  - yarn test test/*_test.mjs test/*/*_test.mjs
